[versions]
androidGradlePlugin = "8.9.2"
androidTools = "31.9.2"
androidxActivity = "1.10.1"
androidxComposeBom = "2025.04.01"
androidxComposeCompiler = "1.5.12"  # Compose VC
androidxLifecycle = "2.8.7"
androidxNavigation = "2.8.9"
baseJunit = "4.13.2"
coreKtxVersion = "1.16.0"
espressoCore = "3.6.1"
hilt = "2.56.1"
hiltNavigation = "1.2.0"
junit = "1.2.1"
kotlin = "2.1.20"
kotlinxSerializationJson = "1.8.0"
ksp = "2.1.20-1.0.31"

[libraries]
# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
# End

# Testing
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
# End

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }
# End

# Kotlin
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
# End

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
junit = { group = "junit", name = "junit", version.ref = "baseJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
# End

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Plugins defined by this project
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
paymentapp-android-application = { id = "paymentapp.android.application", version = "unspecified" }
paymentapp-android-application-compose = { id = "paymentapp.android.application.compose", version = "unspecified" }
paymentapp-android-library = { id = "paymentapp.android.library", version = "unspecified" }
paymentapp-android-library-compose = { id = "paymentapp.android.library.compose", version = "unspecified" }
paymentapp-android-feature = { id = "paymentapp.android.feature", version = "unspecified" }
paymentapp-android-hilt = { id = "paymentapp.android.hilt", version = "unspecified" }
# End
